### ISSUE TITLE
Handle exception when crawling

### ISSUE THREAD

**Issue by mythnc** [mythnc/gbf-backmeup#5]
`class 'urllib3.exceptions.ProtocolError'> ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
INFO:gbf_backmeup.api:end crawl battle data
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 583, in _readinto_chunked
    n = self._safe_readinto(mvb)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 630, in _safe_readinto
    raise IncompleteRead(bytes(mvb[0:total_bytes]), len(b))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 1 more expected)`

**Comment by mythnc** [comment]
ref

1. https://stackoverflow.com/questions/26638329/incompleteread-error-when-retrieving-twitter-data-using-python
2. https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data
3. https://github.com/tweepy/tweepy/issues/448

**Comment by mythnc** [comment]
need to be reproduced
